### ISSUE TITLE
update to go 1.21 (or 1.22)

### ISSUE THREAD

**Issue by miparnisari** [janos/singleflight#9]
See https://go.dev/doc/devel/release#policy

> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. 

go 1.18 isn't supported anymore, we should update to either 1.21 or 1.22

**Comment by janos** [comment]
Yes, that is true, but the `go` directive in `go.mod` specifies only the minimum required go version required to compile packages in this module https://go.dev/doc/modules/gomod-ref#go. Since no features from the newer go versions are used in this package, I think that is still not needed to bump the go version in `go.mod`. Packages that depend on singleflight should be able to compile with any newer go compiler, while allowing potential older project to still use it, even the go support is restricted to the latest two versions.

**Comment by miparnisari** [comment]
@janos today i learnt! thank you!
